apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: apache2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apacha2
        image: apache2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
